# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\VsCodeProjects\PSKO\psko.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PSKO(object):
    def setupUi(self, PSKO):
        PSKO.setObjectName("PSKO")
        PSKO.resize(658, 351)
        self.textEdit_leftPalyers = QtWidgets.QTextEdit(PSKO)
        self.textEdit_leftPalyers.setGeometry(QtCore.QRect(180, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.textEdit_leftPalyers.setFont(font)
        self.textEdit_leftPalyers.setObjectName("textEdit_leftPalyers")
        self.label_leftPlayers = QtWidgets.QLabel(PSKO)
        self.label_leftPlayers.setGeometry(QtCore.QRect(70, 40, 81, 16))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label_leftPlayers.setFont(font)
        self.label_leftPlayers.setObjectName("label_leftPlayers")
        self.label_totalPlayers = QtWidgets.QLabel(PSKO)
        self.label_totalPlayers.setGeometry(QtCore.QRect(70, 90, 81, 16))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label_totalPlayers.setFont(font)
        self.label_totalPlayers.setObjectName("label_totalPlayers")
        self.textEdit_totalPlayers = QtWidgets.QTextEdit(PSKO)
        self.textEdit_totalPlayers.setGeometry(QtCore.QRect(180, 80, 101, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.textEdit_totalPlayers.setFont(font)
        self.textEdit_totalPlayers.setObjectName("textEdit_totalPlayers")
        self.label_startingChips = QtWidgets.QLabel(PSKO)
        self.label_startingChips.setGeometry(QtCore.QRect(70, 140, 81, 16))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label_startingChips.setFont(font)
        self.label_startingChips.setObjectName("label_startingChips")
        self.textEdit_startingChips = QtWidgets.QTextEdit(PSKO)
        self.textEdit_startingChips.setGeometry(QtCore.QRect(180, 130, 101, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.textEdit_startingChips.setFont(font)
        self.textEdit_startingChips.setObjectName("textEdit_startingChips")
        self.textEdit_bountyMagnification = QtWidgets.QTextEdit(PSKO)
        self.textEdit_bountyMagnification.setGeometry(QtCore.QRect(180, 180, 101, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.textEdit_bountyMagnification.setFont(font)
        self.textEdit_bountyMagnification.setObjectName("textEdit_bountyMagnification")
        self.textEdit_curPot = QtWidgets.QTextEdit(PSKO)
        self.textEdit_curPot.setGeometry(QtCore.QRect(180, 230, 101, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.textEdit_curPot.setFont(font)
        self.textEdit_curPot.setObjectName("textEdit_curPot")
        self.textEdit_toCall = QtWidgets.QTextEdit(PSKO)
        self.textEdit_toCall.setGeometry(QtCore.QRect(180, 280, 101, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.textEdit_toCall.setFont(font)
        self.textEdit_toCall.setObjectName("textEdit_toCall")
        self.label_bountyMagnification = QtWidgets.QLabel(PSKO)
        self.label_bountyMagnification.setGeometry(QtCore.QRect(70, 190, 91, 16))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label_bountyMagnification.setFont(font)
        self.label_bountyMagnification.setObjectName("label_bountyMagnification")
        self.label_curPot = QtWidgets.QLabel(PSKO)
        self.label_curPot.setGeometry(QtCore.QRect(70, 240, 81, 16))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label_curPot.setFont(font)
        self.label_curPot.setObjectName("label_curPot")
        self.label_toCall = QtWidgets.QLabel(PSKO)
        self.label_toCall.setGeometry(QtCore.QRect(70, 290, 81, 16))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label_toCall.setFont(font)
        self.label_toCall.setObjectName("label_toCall")
        self.label_equity = QtWidgets.QLabel(PSKO)
        self.label_equity.setGeometry(QtCore.QRect(370, 150, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setItalic(False)
        self.label_equity.setFont(font)
        self.label_equity.setObjectName("label_equity")
        self.textBrowser = QtWidgets.QTextBrowser(PSKO)
        self.textBrowser.setGeometry(QtCore.QRect(320, 180, 181, 61))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.textBrowser.setFont(font)
        self.textBrowser.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textBrowser.setObjectName("textBrowser")
        self.calculateButton = QtWidgets.QPushButton(PSKO)
        self.calculateButton.setGeometry(QtCore.QRect(340, 260, 131, 51))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        self.calculateButton.setFont(font)
        self.calculateButton.setMouseTracking(False)
        self.calculateButton.setIconSize(QtCore.QSize(16, 16))
        self.calculateButton.setObjectName("calculateButton")
        self.rangeButton = QtWidgets.QPushButton(PSKO)
        self.rangeButton.setGeometry(QtCore.QRect(520, 60, 101, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.rangeButton.setFont(font)
        self.rangeButton.setMouseTracking(False)
        self.rangeButton.setIconSize(QtCore.QSize(16, 16))
        self.rangeButton.setObjectName("rangeButton")
        self.range_label = QtWidgets.QLabel(PSKO)
        self.range_label.setGeometry(QtCore.QRect(540, 40, 81, 16))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.range_label.setFont(font)
        self.range_label.setObjectName("range_label")
        self.range_label_2 = QtWidgets.QLabel(PSKO)
        self.range_label_2.setGeometry(QtCore.QRect(560, 100, 81, 16))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.range_label_2.setFont(font)
        self.range_label_2.setObjectName("range_label_2")
        self.rangeButton_2 = QtWidgets.QPushButton(PSKO)
        self.rangeButton_2.setGeometry(QtCore.QRect(520, 120, 101, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.rangeButton_2.setFont(font)
        self.rangeButton_2.setMouseTracking(False)
        self.rangeButton_2.setIconSize(QtCore.QSize(16, 16))
        self.rangeButton_2.setObjectName("rangeButton_2")
        self.rangeButton_3 = QtWidgets.QPushButton(PSKO)
        self.rangeButton_3.setGeometry(QtCore.QRect(520, 180, 101, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.rangeButton_3.setFont(font)
        self.rangeButton_3.setMouseTracking(False)
        self.rangeButton_3.setIconSize(QtCore.QSize(16, 16))
        self.rangeButton_3.setObjectName("rangeButton_3")
        self.range_label_3 = QtWidgets.QLabel(PSKO)
        self.range_label_3.setGeometry(QtCore.QRect(530, 160, 81, 16))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.range_label_3.setFont(font)
        self.range_label_3.setObjectName("range_label_3")
        self.range_label_4 = QtWidgets.QLabel(PSKO)
        self.range_label_4.setGeometry(QtCore.QRect(540, 220, 81, 16))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.range_label_4.setFont(font)
        self.range_label_4.setObjectName("range_label_4")
        self.rangeButton_4 = QtWidgets.QPushButton(PSKO)
        self.rangeButton_4.setGeometry(QtCore.QRect(520, 240, 101, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.rangeButton_4.setFont(font)
        self.rangeButton_4.setMouseTracking(False)
        self.rangeButton_4.setIconSize(QtCore.QSize(16, 16))
        self.rangeButton_4.setObjectName("rangeButton_4")
        self.range_label_5 = QtWidgets.QLabel(PSKO)
        self.range_label_5.setGeometry(QtCore.QRect(540, 280, 81, 16))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.range_label_5.setFont(font)
        self.range_label_5.setObjectName("range_label_5")
        self.rangeButton_5 = QtWidgets.QPushButton(PSKO)
        self.rangeButton_5.setGeometry(QtCore.QRect(520, 300, 101, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.rangeButton_5.setFont(font)
        self.rangeButton_5.setMouseTracking(False)
        self.rangeButton_5.setIconSize(QtCore.QSize(16, 16))
        self.rangeButton_5.setObjectName("rangeButton_5")
        self.label_against_main_range = QtWidgets.QLabel(PSKO)
        self.label_against_main_range.setGeometry(QtCore.QRect(530, 10, 111, 20))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        font.setItalic(False)
        self.label_against_main_range.setFont(font)
        self.label_against_main_range.setObjectName("label_against_main_range")
        self.textBrowser_range = QtWidgets.QTextBrowser(PSKO)
        self.textBrowser_range.setGeometry(QtCore.QRect(300, 20, 201, 121))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.textBrowser_range.setFont(font)
        self.textBrowser_range.setObjectName("textBrowser_range")

        self.retranslateUi(PSKO)
        QtCore.QMetaObject.connectSlotsByName(PSKO)

    def retranslateUi(self, PSKO):
        _translate = QtCore.QCoreApplication.translate
        PSKO.setWindowTitle(_translate("PSKO", "Form"))
        self.textEdit_leftPalyers.setHtml(_translate("PSKO", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'楷体\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_leftPlayers.setText(_translate("PSKO", "剩余玩家"))
        self.label_totalPlayers.setText(_translate("PSKO", "总玩家数"))
        self.label_startingChips.setText(_translate("PSKO", "起始筹码"))
        self.label_bountyMagnification.setText(_translate("PSKO", "赏金倍数"))
        self.label_curPot.setText(_translate("PSKO", "当前底池"))
        self.label_toCall.setText(_translate("PSKO", "需要跟注"))
        self.label_equity.setText(_translate("PSKO", "NeedEquity"))
        self.calculateButton.setText(_translate("PSKO", "计算"))
        self.rangeButton.setText(_translate("PSKO", "显示"))
        self.range_label.setText(_translate("PSKO", "超级紧"))
        self.range_label_2.setText(_translate("PSKO", "紧"))
        self.rangeButton_2.setText(_translate("PSKO", "显示"))
        self.rangeButton_3.setText(_translate("PSKO", "显示"))
        self.range_label_3.setText(_translate("PSKO", "标准范围"))
        self.range_label_4.setText(_translate("PSKO", "宽范围"))
        self.rangeButton_4.setText(_translate("PSKO", "显示"))
        self.range_label_5.setText(_translate("PSKO", "超级宽"))
        self.rangeButton_5.setText(_translate("PSKO", "显示"))
        self.label_against_main_range.setText(_translate("PSKO", "对手的范围"))

