# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\VsCodeProjects\PSKO\psko.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(551, 351)
        self.textEdit_leftPalyers = QtWidgets.QTextEdit(Form)
        self.textEdit_leftPalyers.setGeometry(QtCore.QRect(180, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.textEdit_leftPalyers.setFont(font)
        self.textEdit_leftPalyers.setObjectName("textEdit_leftPalyers")
        self.label_leftPlayers = QtWidgets.QLabel(Form)
        self.label_leftPlayers.setGeometry(QtCore.QRect(70, 40, 81, 16))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label_leftPlayers.setFont(font)
        self.label_leftPlayers.setObjectName("label_leftPlayers")
        self.label_totalPlayers = QtWidgets.QLabel(Form)
        self.label_totalPlayers.setGeometry(QtCore.QRect(70, 90, 81, 16))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label_totalPlayers.setFont(font)
        self.label_totalPlayers.setObjectName("label_totalPlayers")
        self.textEdit_totalPlayers = QtWidgets.QTextEdit(Form)
        self.textEdit_totalPlayers.setGeometry(QtCore.QRect(180, 80, 101, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.textEdit_totalPlayers.setFont(font)
        self.textEdit_totalPlayers.setObjectName("textEdit_totalPlayers")
        self.label_startingChips = QtWidgets.QLabel(Form)
        self.label_startingChips.setGeometry(QtCore.QRect(70, 140, 81, 16))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label_startingChips.setFont(font)
        self.label_startingChips.setObjectName("label_startingChips")
        self.textEdit_startingChips = QtWidgets.QTextEdit(Form)
        self.textEdit_startingChips.setGeometry(QtCore.QRect(180, 130, 101, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.textEdit_startingChips.setFont(font)
        self.textEdit_startingChips.setObjectName("textEdit_startingChips")
        self.textEdit_bountyMagnification = QtWidgets.QTextEdit(Form)
        self.textEdit_bountyMagnification.setGeometry(QtCore.QRect(180, 180, 101, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.textEdit_bountyMagnification.setFont(font)
        self.textEdit_bountyMagnification.setObjectName("textEdit_bountyMagnification")
        self.textEdit_curPot = QtWidgets.QTextEdit(Form)
        self.textEdit_curPot.setGeometry(QtCore.QRect(180, 230, 101, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.textEdit_curPot.setFont(font)
        self.textEdit_curPot.setObjectName("textEdit_curPot")
        self.textEdit_toCall = QtWidgets.QTextEdit(Form)
        self.textEdit_toCall.setGeometry(QtCore.QRect(180, 280, 101, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.textEdit_toCall.setFont(font)
        self.textEdit_toCall.setObjectName("textEdit_toCall")
        self.label_bountyMagnification = QtWidgets.QLabel(Form)
        self.label_bountyMagnification.setGeometry(QtCore.QRect(70, 190, 91, 16))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label_bountyMagnification.setFont(font)
        self.label_bountyMagnification.setObjectName("label_bountyMagnification")
        self.label_curPot = QtWidgets.QLabel(Form)
        self.label_curPot.setGeometry(QtCore.QRect(70, 240, 81, 16))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label_curPot.setFont(font)
        self.label_curPot.setObjectName("label_curPot")
        self.label_toCall = QtWidgets.QLabel(Form)
        self.label_toCall.setGeometry(QtCore.QRect(70, 290, 81, 16))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label_toCall.setFont(font)
        self.label_toCall.setObjectName("label_toCall")
        self.label_equity = QtWidgets.QLabel(Form)
        self.label_equity.setGeometry(QtCore.QRect(363, 40, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setItalic(False)
        self.label_equity.setFont(font)
        self.label_equity.setObjectName("label_equity")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(320, 70, 181, 131))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.textBrowser.setFont(font)
        self.textBrowser.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textBrowser.setObjectName("textBrowser")
        self.calculateButton = QtWidgets.QPushButton(Form)
        self.calculateButton.setGeometry(QtCore.QRect(340, 250, 131, 51))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        self.calculateButton.setFont(font)
        self.calculateButton.setMouseTracking(False)
        self.calculateButton.setIconSize(QtCore.QSize(16, 16))
        self.calculateButton.setObjectName("calculateButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_leftPlayers.setText(_translate("Form", "剩余玩家"))
        self.label_totalPlayers.setText(_translate("Form", "总玩家数"))
        self.label_startingChips.setText(_translate("Form", "起始筹码"))
        self.label_bountyMagnification.setText(_translate("Form", "赏金倍数"))
        self.label_curPot.setText(_translate("Form", "当前底池"))
        self.label_toCall.setText(_translate("Form", "需要跟注"))
        self.label_equity.setText(_translate("Form", "NeedEquity"))
        self.calculateButton.setText(_translate("Form", "计算"))

